API_LOGIN = '/login'
API_GET_VERSION = '/api/version'

API_GET_PROCESS_LIST = '/api/processes'
API_GET_PROCESS_DETAIL = '/api/processes/{pid}'
API_KILL_PROCESS = '/api/processes/{pid}/kill'
API_EDIT_PROCESS = '/api/processes/{pid}/edit'
API_SUSPEND_PROCESS = '/api/processes/{pid}/suspend'
API_RESUME_PROCESS = '/api/processes/{pid}/resume'

API_GET_USER_LIST = '/api/users'
API_GET_USER_DETAIL = '/api/users/{username}'
API_ADD_USER = '/api/users'
API_EDIT_USER = '/api/users/{username}'
API_DELETE_USER = '/api/users/{username}'
API_DUPLICATE_USER = '/api/users/{username}/duplicate'
API_ENABLE_USER = '/api/users/{username}/enable'
API_DISABLE_USER = '/api/users/{username}/disable'

API_GET_SYSTEM_INFO = '/api/getsyi'
API_GET_SYSTEM_RESOURCES = '/api/getrmi'

API_GET_ALL_LICENSES_LIST = '/api/licenses'
API_GET_ACTIVE_LICENSES_LIST = '/api/licenses?active'
API_GET_LICENSE = '/api/licenses/{product}/{authorization}'
API_GET_LICENSE_HISTORY = '/api/licenses/{product}/{authorization}/history'
API_DELETE_LICENSE_HISTORY = '/api/licenses/{product}/{authorization}/history'
API_EXPORT_LICENSE_HISTORY = '/api/licenses/{product}/{authorization}/history/export'
API_ENABLE_LICENSE = '/api/licenses/{product}/{authorization}/enable'
API_DISABLE_LICENSE = '/api/licenses/{product}/{authorization}/disable'
API_DELETE_LICENSE = '/api/licenses/{product}/{authorization}'
API_LOAD_LICENSE = '/api/licenses/{product}/{authorization}/load'
API_UNLOAD_LICENSE = '/api/licenses/{product}/unload'
API_REGISTER_LICENSE = '/api/licenses/{product}/register'

API_GET_DISKS = '/api/disks'
API_GET_DISK_DETAIL = '/api/disks/{device}'

API_GET_REPORTS = '/api/reports'
API_GET_REPORT = '/api/reports/{filename}?fileDir={directory}'
API_EXPORT_REPORT = '/api/reports/{filename}/export?fileDir={directory}'
API_GET_REPORT_LOG = '/api/reports/{filename}/export?fileDir={directory}'
API_GENERATE_REPORTS = '/api/reports'

API_GET_NODES = '/api/nodes'